name: Changesets Version Bump

on:
  push:
    branches: [main]
  workflow_dispatch:


jobs:
  version:
    name: Create Version Bump PR
    runs-on: ubuntu-latest

    # Remove this once we setup react-native-sdk[bot] with this repo
    permissions:
      contents: write # for GH releases and Git tags (Changesets)
      pull-requests: write # version PRs (Changesets)

    if: ${{ github.repository == 'microsoft/fluentui-react-native' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up toolchain
        uses: microsoft/react-native-test-app/.github/actions/setup-toolchain@5.0.14

      - name: Install dependencies
        run: |
          yarn install --immutable

      - name: Build packages
        run: yarn buildci

      # Bring this back once we setup react-native-sdk[bot] with this repo
      # - name: Generate token for version PR
      #   uses: actions/create-github-app-token@v2
      #   id: app-token
      #   with:
      #     app-id: ${{ vars.APP_ID }}
      #     private-key: ${{ secrets.PRIVATE_KEY }}
      #     permissions: |
      #       contents: write
      #       pull-requests: write

      - name: Create Version Bump PR
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn changeset:version
          commit: 'chore(release): version packages'
          title: 'chore(release): version packages'
          createGithubReleases: false
        env:
          # Switch token once we setup react-native-sdk[bot] with this repo
          # GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Post-version hook for dependency-profiles
        if: steps.changesets.outputs.hasChangesets == 'true'
        run: node scripts/update-dependency-profiles-postbump.mts
