name: Changesets Version Bump

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  version:
    name: Create Version Bump PR
    runs-on: ubuntu-latest

    if: ${{ github.repository == 'microsoft/fluentui-react-native' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up toolchain
        uses: microsoft/react-native-test-app/.github/actions/setup-toolchain@5.0.14

      - name: Install dependencies
        run: |
          yarn install --immutable

      - name: Build packages
        run: yarn buildci

      - name: Generate token for version PR
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          permission-contents: write # for GH releases and Git tags (Changesets)
          permission-pull-requests: write # version PRs (Changesets)

      - name: Create Version Bump PR
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn changeset:version
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
